---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	chat(chat)
	gui_control(gui_control)
	gui_control_tools(gui_control_tools)
	system(system)
	system_tools(system_tools)
	communication(communication)
	communication_tools(communication_tools)
	calendar(calendar)
	calendar_tools(calendar_tools)
	info(info)
	info_tools(info_tools)
	media_control(media_control)
	media_control_tools(media_control_tools)
	dedicated_tool_spotify(dedicated_tool_spotify)
	dedicated_tool_spotify_tools(dedicated_tool_spotify_tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	calendar -.-> __end__;
	calendar -. &nbsp;tools&nbsp; .-> calendar_tools;
	calendar_tools --> calendar;
	communication -.-> __end__;
	communication -. &nbsp;tools&nbsp; .-> communication_tools;
	communication_tools --> communication;
	dedicated_tool_spotify -.-> __end__;
	dedicated_tool_spotify -. &nbsp;tools&nbsp; .-> dedicated_tool_spotify_tools;
	dedicated_tool_spotify_tools --> dedicated_tool_spotify;
	gui_control -.-> __end__;
	gui_control -. &nbsp;tools&nbsp; .-> gui_control_tools;
	gui_control_tools --> gui_control;
	info -.-> __end__;
	info -. &nbsp;tools&nbsp; .-> info_tools;
	info_tools --> info;
	media_control -.-> __end__;
	media_control -. &nbsp;tools&nbsp; .-> media_control_tools;
	media_control_tools --> media_control;
	router -.-> calendar;
	router -.-> chat;
	router -.-> communication;
	router -.-> dedicated_tool_spotify;
	router -.-> gui_control;
	router -.-> info;
	router -. &nbsp;media&nbsp; .-> media_control;
	router -.-> system;
	system -.-> __end__;
	system -. &nbsp;tools&nbsp; .-> system_tools;
	system_tools --> system;
	chat --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
